language: swift
osx_image: xcode10.2
branches:
  only:
    - master
before_install:
  - gem install fastlane --no-document --quiet
install: true
script:
  - pod install
  - fastlane scan --scheme "TAU" --device "iPhone X" --clean --verbose
