language: swift
osx_image: xcode10.2
branches:
  only:
    - master
before_install:
  - gem install fastlane --no-ri --no-rdoc --no-document
install: true
script:
  - fastlane scan --scheme "TAU" --device "iPhone XR" --clean
